"""Load and validate ACF field mapping files generated by the parser."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


class FieldMapping:
    """Loaded field mapping for a WordPress site.

    Provides lookup methods for layout fields, making the raw mapping
    JSON easy to work with in the transformer and other components.
    """

    def __init__(self, data: dict[str, Any]):
        self.flexible_content_key: str = data["flexible_content_key"]
        self.layouts: dict[str, dict] = data["layouts"]

    def get_layout(self, layout_name: str) -> dict | None:
        """Get a layout by name, or None if not found."""
        return self.layouts.get(layout_name)

    def get_layout_fields(self, layout_name: str) -> dict[str, Any]:
        """Get the fields dict for a layout. Returns empty dict if not found."""
        layout = self.layouts.get(layout_name)
        if layout is None:
            return {}
        return layout.get("fields", {})

    def get_layout_key(self, layout_name: str) -> str | None:
        """Get the layout_key for a named layout."""
        layout = self.layouts.get(layout_name)
        if layout is None:
            return None
        return layout.get("layout_key")

    def list_layouts(self) -> list[str]:
        """Return sorted list of all layout names."""
        return sorted(self.layouts.keys())

    def has_layout(self, layout_name: str) -> bool:
        return layout_name in self.layouts


def load_mapping(filepath: str | Path) -> FieldMapping:
    """Load a field mapping JSON file and return a FieldMapping instance.

    Args:
        filepath: Path to the mapping JSON file.

    Returns:
        FieldMapping instance ready for use.

    Raises:
        FileNotFoundError: If the mapping file doesn't exist.
        ValueError: If the mapping file is malformed.
    """
    filepath = Path(filepath)

    with filepath.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if "flexible_content_key" not in data:
        raise ValueError(f"Missing 'flexible_content_key' in {filepath}")
    if "layouts" not in data:
        raise ValueError(f"Missing 'layouts' in {filepath}")

    logger.info(
        "Loaded mapping from %s (%d layouts)",
        filepath,
        len(data["layouts"]),
    )

    return FieldMapping(data)
